wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    code_path: code/textile_classification.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
